# Generated by Django 4.1.1 on 2023-07-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_user_image'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='review_photos', to='coreapp.document'),
        ),
    ]
