# Generated by Django 4.1.1 on 2023-07-12 12:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_review_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fist_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2023, 7, 12, 12, 34, 30, 403102, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
