# Generated by Django 4.1.1 on 2023-07-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_review_fist_name_review_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='fist_name',
        ),
        migrations.AddField(
            model_name='review',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
