# Generated by Django 4.1.1 on 2023-07-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_remove_review_fist_name_review_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='last_name',
        ),
    ]
