# Generated by Django 4.1.1 on 2023-07-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_remove_review_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
