# Generated by Django 4.1.1 on 2023-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='main_category',
            field=models.SmallIntegerField(choices=[(0, 'Home Decor'), (1, 'In Style')], default=0),
        ),
    ]
