# Generated by Django 4.1.1 on 2023-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_billinginfo_options_alter_country_options_and_more'),
        ('promotions', '0008_banner_main_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='review',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='review_photos', to='coreapp.document'),
        ),
    ]
