# Generated by Django 4.1.1 on 2023-10-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_alter_offer_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
