# Generated by Django 4.1.1 on 2023-10-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0011_alter_banner_options_banner_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
