# Generated by Django 4.1.1 on 2023-06-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default/user_placeholder.jpg', null=True, upload_to='user/profile'),
        ),
    ]
