# Generated by Django 4.1.1 on 2023-07-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_user_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
