# Generated by Django 4.1.1 on 2023-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_user_blood_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginfo',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='userconfirmation',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
