# Generated by Django 4.1.1 on 2023-08-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_alter_billinginfo_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
