# Generated by Django 4.1.1 on 2023-09-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_document_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='division',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
