# Generated by Django 4.1.1 on 2023-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_document_resize_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='document',
            name='width',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='document',
            name='resize_document',
            field=models.FileField(blank=True, upload_to='documents/resized/%Y/%m/%d/'),
        ),
    ]
