# Generated by Django 4.1.1 on 2023-09-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_outlet'),
        ('coreapp', '0011_document_height_document_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_outlet_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.outlet'),
        ),
    ]
