# Generated by Django 4.1.1 on 2023-10-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0015_redexdivision_redexdistrict_redexarea'),
        ('coreapp', '0012_user_is_outlet_user_user_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='redex_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.redexarea'),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='redex_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.redexdistrict'),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='redex_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.redexdivision'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='postcode_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='state_county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='town_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
