# Generated by Django 4.1.1 on 2023-06-22 09:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('value', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_values', to='inventory.attributes')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('level', models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)])),
                ('main_category', models.SmallIntegerField(choices=[(0, 'Home Decor'), (1, 'In Style')])),
                ('category_type', models.SmallIntegerField(choices=[(0, 'Main Category'), (1, 'Sub Main Category'), (2, 'Other Category')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.document')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('to_address', models.CharField(max_length=350)),
                ('to_address2', models.CharField(blank=True, max_length=350, null=True)),
                ('to_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('to_city', models.CharField(blank=True, max_length=50, null=True)),
                ('to_division', models.CharField(blank=True, max_length=50, null=True)),
                ('to_district', models.CharField(blank=True, max_length=50, null=True)),
                ('to_country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('attribute_value', models.ManyToManyField(blank=True, to='inventory.attributevalue')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('pid', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('main_category', models.SmallIntegerField(choices=[(0, 'Home Decor'), (1, 'In Style')])),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('stock', models.IntegerField()),
                ('barcode', models.ImageField(blank=True, upload_to='bar_codes/products/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/products/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumb_resized', models.ImageField(blank=True, upload_to='products/thumb_resized/')),
                ('minimum_quantity', models.IntegerField(default=0)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('vendor_info', models.TextField(blank=True, null=True)),
                ('about_brand', models.TextField(blank=True, null=True)),
                ('shipping_info', models.TextField(blank=True, null=True)),
                ('variants_json', models.JSONField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='inventory.category')),
                ('feature_images', models.ManyToManyField(blank=True, related_name='feature_images', to='coreapp.document')),
                ('tags', models.ManyToManyField(blank=True, to='inventory.tags')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.document')),
                ('variant', models.ManyToManyField(blank=True, to='inventory.variant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
