# Generated by Django 4.1.1 on 2023-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=200),
        ),
    ]
