# Generated by Django 4.1.1 on 2023-07-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_products_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('?',)},
        ),
    ]
