# Generated by Django 4.1.1 on 2023-07-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_user_blood_group'),
        ('inventory', '0007_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='thumb2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb2', to='coreapp.document'),
        ),
        migrations.AlterField(
            model_name='products',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='coreapp.document'),
        ),
    ]
