# Generated by Django 4.1.1 on 2023-07-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_products_thumb2_alter_products_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ('created_at',)},
        ),
    ]
