# Generated by Django 4.1.1 on 2023-07-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_attributevalue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
