# Generated by Django 4.1.1 on 2023-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_products_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
