# Generated by Django 4.1.1 on 2023-08-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_products_is_trending_products_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-created_at',)},
        ),
    ]
