# Generated by Django 4.1.1 on 2023-08-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_products_variant_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_from_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
