# Generated by Django 4.1.1 on 2023-08-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_show_website',
            field=models.BooleanField(default=True),
        ),
    ]
