# Generated by Django 4.1.1 on 2023-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_alter_billinginfo_last_name'),
        ('inventory', '0016_products_is_show_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='images',
            field=models.ManyToManyField(blank=True, to='coreapp.document'),
        ),
    ]
