# Generated by Django 4.1.1 on 2023-08-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_variant_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='inventory.products'),
        ),
    ]
