# Generated by Django 4.1.1 on 2023-09-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_outlet'),
        ('inventory', '0020_outletvariant_outletproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletproducts',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.outlet'),
            preserve_default=False,
        ),
    ]
