# Generated by Django 4.1.1 on 2023-09-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_invoice_outlet'),
        ('inventory', '0021_outletproducts_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletvariant',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.outlet'),
            preserve_default=False,
        ),
    ]
