# Generated by Django 4.1.1 on 2023-10-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_outletproducts_stock_alter_outletvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='barcode_modified',
            field=models.ImageField(blank=True, upload_to='bar_codes/products/'),
        ),
    ]
