# Generated by Django 4.1.1 on 2023-11-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', '-created_at')},
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=9999),
        ),
    ]
