# Generated by Django 4.1.1 on 2023-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_display_center_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_center',
            name='location_url',
            field=models.URLField(),
        ),
    ]
