# Generated by Django 4.1.1 on 2023-07-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_alter_display_center_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_center',
            name='location',
        ),
    ]
