# Generated by Django 4.1.1 on 2023-07-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='blob_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
