# Generated by Django 4.1.1 on 2023-07-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_page_blob_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='blob_url',
        ),
    ]
