# Generated by Django 4.1.1 on 2023-09-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_remove_page_blob_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardnotification',
            name='notification',
            field=models.SmallIntegerField(default=0),
        ),
    ]
