# Generated by Django 4.1.1 on 2023-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_document_height_document_width_and_more'),
        ('utility', '0010_dashboardnotification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='brand_images',
            field=models.ManyToManyField(blank=True, related_name='brand_images', to='coreapp.document'),
        ),
    ]
