# Generated by Django 4.1.1 on 2023-10-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_alter_globalsettings_brand_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('division_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bn_name', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upazila', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('postCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('district_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('price', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('upazilla', models.ManyToManyField(related_name='upazilla', to='utility.upazilla')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
