# Generated by Django 4.1.1 on 2023-10-04 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0012_district_division_postcode_upazilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdeliverycharge',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='inside_dhaka',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='is_free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='outside_dhaka',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
    ]
