# Generated by Django 4.1.1 on 2023-10-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0013_customdeliverycharge_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdeliverycharge',
            name='price',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='inside_dhaka',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='outside_dhaka',
            field=models.IntegerField(default=150),
        ),
    ]
