# Generated by Django 4.1.1 on 2023-10-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0014_alter_customdeliverycharge_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedexDivision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RedexDistrict',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.redexdivision')),
            ],
        ),
        migrations.CreateModel(
            name='RedexArea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inside_dhaka', models.BooleanField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.redexdistrict')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.redexdivision')),
            ],
        ),
    ]
