# Generated by Django 4.1.1 on 2023-11-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0015_redexdivision_redexdistrict_redexarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
