# Generated by Django 4.1.1 on 2023-07-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-created_at',)},
        ),
    ]
