# Generated by Django 4.1.1 on 2023-08-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_user_alter_checkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='success_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_type',
            field=models.SmallIntegerField(choices=[(0, 'Inside Dhaka : 80/-'), (1, 'Outside Dhaka : 150/-'), (2, 'Custom')]),
        ),
    ]
