# Generated by Django 4.1.1 on 2023-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_checkout_success_url_alter_checkout_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shipping_division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
