# Generated by Django 4.1.1 on 2023-09-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cart_user_alter_checkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
