# Generated by Django 4.1.1 on 2023-06-22 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('variant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.products')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.variant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/invoice/')),
                ('qr_code_text', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('source', models.SmallIntegerField(choices=[(0, 'Ecommerce Website'), (1, 'Inventory'), (2, 'Admin Panel')], default=1)),
                ('invoice_date', models.DateField()),
                ('bill_from', models.CharField(default='KAARUJ', max_length=50)),
                ('bill_to', models.CharField(max_length=50)),
                ('from_mobile', models.CharField(default='+8801980907892', max_length=50)),
                ('to_mobile', models.CharField(max_length=50)),
                ('from_email', models.CharField(default='kaarujbangladesh@gmail.com', max_length=150)),
                ('to_email', models.CharField(blank=True, max_length=150, null=True)),
                ('from_address', models.CharField(default='House 148, Block- B, Road 5, Basundhara R/A, Dhaka, Bangladesh', max_length=350)),
                ('to_address', models.CharField(max_length=350)),
                ('to_address2', models.CharField(blank=True, max_length=350, null=True)),
                ('to_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('to_city', models.CharField(blank=True, max_length=50, null=True)),
                ('to_division', models.CharField(blank=True, max_length=50, null=True)),
                ('to_district', models.CharField(blank=True, max_length=50, null=True)),
                ('to_country', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_type', models.SmallIntegerField(choices=[(0, 'Regular'), (1, 'Urgent')])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_charge_type', models.SmallIntegerField(choices=[(0, 'Inside Dhaka : 80/-'), (1, 'Outside Dhaka : 150/-'), (2, 'Custom')])),
                ('payment_type', models.SmallIntegerField(choices=[(0, 'Cash On Delivery'), (1, 'SSLCOMMERZ')])),
                ('discount_type', models.SmallIntegerField(choices=[(0, 'Flat'), (1, 'Percentage')])),
                ('delivery_status', models.SmallIntegerField(choices=[(0, 'Returned'), (1, 'Recieved'), (2, 'Delivered'), (3, 'Pending'), (4, 'Hold'), (5, 'Dispatched')])),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.SmallIntegerField(choices=[(0, 'Paid'), (1, 'Unpaid'), (2, 'Due')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('product_list_json', models.JSONField(blank=True, null=True)),
                ('invoice_view_json', models.JSONField(blank=True, null=True)),
                ('send_pdf', models.BooleanField()),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('banK_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('banK_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('banK_branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bkash_number', models.CharField(blank=True, max_length=11, null=True)),
                ('bkash_trx_number', models.CharField(blank=True, max_length=11, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('created_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_created_for', to=settings.AUTH_USER_MODEL)),
                ('invoice_products', models.ManyToManyField(blank=True, to='sales.invoice_products')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.CharField(max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
