# Generated by Django 4.1.1 on 2023-06-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_stock_updated_after_return',
            field=models.BooleanField(default=False),
        ),
    ]
