# Generated by Django 4.1.1 on 2023-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_invoice_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exchange_products_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_purchase_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_stock_updated_after_exchanged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nagad_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nagad_trx_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice_products',
            name='is_purchase_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_status',
            field=models.SmallIntegerField(choices=[(0, 'Returned'), (1, 'Order Placed'), (2, 'Delivered'), (3, 'Pending'), (4, 'Hold'), (5, 'Dispatched'), (6, 'Exchanged')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, 'Cash On Delivery'), (1, 'SSLCOMMERZ'), (2, 'Bkash'), (3, 'Bank'), (4, 'Card'), (5, 'Nagad'), (6, 'Kaaruj Delivery')]),
        ),
    ]
