# Generated by Django 4.1.1 on 2023-07-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoice_exchange_products_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, 'Cash On Delivery'), (1, 'Card'), (2, 'Bank'), (3, 'Bkash'), (4, 'SSLECOMMERZ'), (5, 'Nagad'), (6, 'Kaaruj Delivery')]),
        ),
    ]
