# Generated by Django 4.1.1 on 2023-07-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_invoice_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='is_purchase_order',
            field=models.BooleanField(default=False),
        ),
    ]
