# Generated by Django 4.1.1 on 2023-09-06 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0008_invoice_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_requisition_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
