# Generated by Django 4.1.1 on 2023-09-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_invoice_is_requisition_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_products',
            name='is_requisition_order',
            field=models.BooleanField(default=False),
        ),
    ]
