# Generated by Django 4.1.1 on 2023-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_invoice_products_is_requisition_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='is_requisition_order',
            field=models.BooleanField(default=False),
        ),
    ]
