# Generated by Django 4.1.1 on 2023-09-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_dailyreport_is_requisition_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='from_address',
            field=models.CharField(default='Road: 42, Gulshan 2, Dhaka, Bangladesh', max_length=350),
        ),
    ]
