# Generated by Django 4.1.1 on 2023-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_invoice_from_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='send_pdf_admin',
            field=models.BooleanField(default=False),
        ),
    ]
