# Generated by Django 4.1.1 on 2023-09-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_invoice_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='is_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.outlet'),
        ),
        migrations.AddField(
            model_name='invoice_products',
            name='is_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_products',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.outlet'),
        ),
    ]
