# Generated by Django 4.1.1 on 2023-09-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_dailyreport_is_outlet_dailyreport_outlet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_outlet',
            field=models.BooleanField(default=False),
        ),
    ]
