# Generated by Django 4.1.1 on 2023-10-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_invoice_is_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_products',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_regular',
            field=models.BooleanField(default=True),
        ),
    ]
