# Generated by Django 4.1.1 on 2023-10-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_invoice_products_is_regular_alter_invoice_is_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
    ]
