# Generated by Django 4.1.1 on 2023-10-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_dailyreport_is_regular_alter_invoice_is_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mixed_payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
