# Generated by Django 4.1.1 on 2023-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_invoice_mixed_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(0, 'Paid'), (1, 'Unpaid'), (2, 'Due'), (3, 'Exchanged')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, 'Cash On Delivery'), (1, 'Card'), (2, 'Bank'), (3, 'Bkash'), (4, 'SSLECOMMERZ'), (5, 'Nagad'), (6, 'Kaaruj Delivery'), (7, 'Rocket'), (8, 'Mixed')]),
        ),
    ]
