# Generated by Django 4.1.1 on 2023-10-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_invoice_redex_area_invoice_redex_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='location',
            field=models.TextField(blank=True, default='Dhaka,Bangladesh', null=True),
        ),
    ]
