# Generated by Django 4.1.1 on 2023-10-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_chalan'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalan',
            name='is_chalan_outlet_products_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chalan',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bill_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_address',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
