# Generated by Django 4.1.1 on 2023-10-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_chalan_is_chalan_outlet_products_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_convert_to_regular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_products',
            name='is_convert_to_regular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_products',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
